name: base_project
description: Module base project.
publish_to: none 

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.0
  cupertino_icons: ^1.0.8 
  flutter_bloc: ^8.0.1   
  google_fonts: ^6.1.0 
  json_annotation: ^4.6.0 
  dio: ^5.0.1    
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  #log
  logger: any

  # loading
  flutter_easyloading: ^3.0.5

  #get app PATH
  package_info_plus: ^8.0.2
  
  #theme 
  nb_utils: ^7.0.7 
  fluent_ui: ^4.4.0
  json_theme: ^7.0.0

  # Cache http
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^4.0.0
  hive: ^2.2.3 
  pretty_dio_logger: ^1.3.1
 
  #UI
  cached_network_image: ^3.2.2
  flutter_svg: ^2.0.1   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.5
  freezed: ^2.5.7
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/logo/ 
